server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://127.0.0.1:5432/storage
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
